#spring:
#  profiles:
#    active: dev

spring:
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 172.18.91.89:8848
        extension-configs:
          - data-id: alibaba-sentinel-client-rules
            group: SENTINEL_GROUP
            refresh: true
  config:
    import:
      - nacos:server-product-dev.yml