#spring:
#  profiles:
#    active: dev

spring:
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 172.18.91.89:8848
  config:
    import:
      - nacos:server-order-dev.yml